version: '3.9'

services:
  api_entrega_s3:
    container_name: api_entrega_s3
    build: .
    ports: 
      - 3333:3333
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=Digo
      - POSTGRES_PASSWORD=Digo020820
      - POSTGRES_DB=products_management
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Digo -d products_management"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    